services:

  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: git-scraper
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongo
