
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-scraper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: git-scraper
  template:
    metadata:
      labels:
        app: git-scraper
    spec:
      containers:
        - name: git-scraper
          image: git-scraper:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/mydatabase?replicaSet=rs0"



